#
# This is free software, lisence use MIT.
#
# Copyright (C) 2019 P3TERX <https://p3terx.com>
#
# Copyright (C) 2020 KFERMercer <KFER.Mercer@gmail.com>
#
# <https://github.com/KFERMercer/OpenWrt-CI>
#

name: Build OpenWrt

on:
  workflow_dispatch:
    inputs:
      config_file:
        description: '选择.config配置文件'
        required: true
        default: 'H3C.config'
        type: choice
        options:
          - H3C.config
          - XG1.config
      hostname:
        description: '选择主机名'
        required: true
        default: 'NX30Pro'
        type: choice
        options:
          - NX30Pro
          - XG1

env:
  SELECTED_CONFIG: ${{ github.event.inputs.config_file }}
  SELECTED_HOSTNAME: ${{ github.event.inputs.hostname }}
  OPENWRT_SOURCE_DIR: openwrt # 定义OpenWrt源代码目录

jobs:
  build:
    runs-on: ubuntu-22.04
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
      - name: 检查代码
        uses: actions/checkout@v4

      - name: 初始化环境
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo -E apt-get update -yqq
          sudo -E apt-get install -yqq build-essential asciidoc binutils bzip2 lib32gcc-s1 gawk gettext git libncurses5-dev libz-dev patch python3 unzip zlib1g-dev libc6-dev-i386 subversion flex uglifyjs git-core gcc-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler g++-multilib
          sudo -E apt-get autoremove --purge -yqq
          sudo -E apt-get clean -yqq

      - name: 克隆OpenWrt源代码
        run: |
          git clone https://github.com/coolsnowwolf/lede ${{ env.OPENWRT_SOURCE_DIR }}

      - name: 加载自定义源
        working-directory: ${{ env.OPENWRT_SOURCE_DIR }}
        run: |
          # echo "src-git passwall_packages https://github.com/xiaorouji/openwrt-passwall-packages.git;main" >> feeds.conf.default
          # echo "src-git passwall https://github.com/xiaorouji/openwrt-passwall.git;main" >> feeds.conf.default

      - name: 更新软件源
        working-directory: ${{ env.OPENWRT_SOURCE_DIR }}
        run: |
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: 应用选择的配置文件
        working-directory: ${{ env.OPENWRT_SOURCE_DIR }}
        run: |
          echo "使用配置文件: ${{ env.SELECTED_CONFIG }}"
          # 将配置文件从 'configs/' 目录复制到 OpenWrt 根目录
          cp "../configs/${{ env.SELECTED_CONFIG }}" .config
          echo "已应用配置文件: ../configs/${{ env.SELECTED_CONFIG }}"

      - name: 加载配置并修改
        working-directory: ${{ env.OPENWRT_SOURCE_DIR }}
        run: |
          # 1.修改默认ip
          sed -i 's/192.168.1.1/192.168.2.1/g' package/base-files/files/bin/config_generate
          # 2.修改主机名
          sed -i "s/OpenWrt/$SELECTED_HOSTNAME/g" package/base-files/files/bin/config_generate
          # 3.修改版本号
          sed -i "s/OpenWrt /0012h build $(TZ=UTC-8 date "+%Y.%m.%d") @ OpenWrt /g" package/lean/default-settings/files/zzz-default-settings
          # 4.修改默认主题
          sed -i ' s/luci-theme-bootstrap/luci-theme-argon/g ' feeds/luci/collections/luci/Makefile
          # 5.设置ttyd免登录
          sed -i 's/exit 0/exit 0\nsed -i "s/\\/bin\\/login/\\/bin\\/login -f root/" \/etc\/config\/ttyd/' package/lean/default-settings/files/zzz-default-settings

      - name: 下载依赖包
        working-directory: ${{ env.OPENWRT_SOURCE_DIR }}
        run: |
          make defconfig
          make download -j$(nproc) # 使用所有核心下载依赖
          find dl -size -1024c -exec ls -l {} \;
          find dl -size -1024c -exec rm -f {} \;

      - name: 编译固件
        working-directory: ${{ env.OPENWRT_SOURCE_DIR }}
        run: |
          echo -e "$(nproc) thread build."
          make -j$(nproc) V=s

      - name : 上传编译目录
        uses: actions/upload-artifact@v4
        with:
          name: OpenWrt_firmware
          path: ${{ env.OPENWRT_SOURCE_DIR }}/bin/targets/

      - name: 生成发布标签
        id: tag
        run: |
          echo "release_tag=$(date +"%Y.%m.%d-%H%M")" >> $GITHUB_OUTPUT
          echo "OpenWrt Firmware" > release.txt
          echo "" >> release.txt
          echo "Build Date: $(date +"%Y-%m-%d %H:%M:%S %Z")" >> release.txt
          echo "Selected Config: ${{ env.SELECTED_CONFIG }}" >> release.txt
          echo "Selected Hostname: ${{ env.SELECTED_HOSTNAME }}" >> release.txt
          echo "status=success" >> $GITHUB_OUTPUT

      - name: 上传固件到发布版
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.tag.outputs.release_tag }}
          body_path: release.txt
          files: ${{ env.OPENWRT_SOURCE_DIR }}/bin/targets/*/*/*

      - name: 删除旧工作流运行
        uses: Mattraks/delete-workflow-runs@v2.0.1
        with:
          retain_days: 1
          keep_minimum_runs: 2

      - name: 移除旧发布版
        uses: dev-drprasad/delete-older-releases@v0.2.1
        with:
          keep_latest: 3
          delete_tags: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
